# Generated by Django 3.1 on 2020-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_profilemanager'),
        ('posts', '0004_remove_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='post_likes', through='posts.Like', to='profiles.Profile'),
        ),
    ]
