# Generated by Django 3.1 on 2020-08-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200824_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileManager',
        ),
    ]
